### ISSUE TITLE
Checklist for facilitator

### ISSUE THREAD

**Issue by 149203** [149203/developersvegas2#11]
This is a checklist for everything the facilitator should say during Demo Day:

- [ ] How to sign up / assist anyone that needs it
- [ ] Read the names of presenters at 12:25pm
- [ ] Where the presenter can see the timer
- [ ] Presenters please stay in frame
- [ ] Announcement policy
- [ ] Read any announcements
